### ISSUE TITLE
exiD lane_markings yaml files

### ISSUE THREAD

**Issue by luwen2024** [SajjadMzf/TrajPreprocess#1]
Hi Sajjad,
Could you upload the codes to generate '!lane_markings_yml' files please? Or can you share more details about the format of the lane marking files. Thx!

**Comment by SajjadMzf** [comment]
Hi Luwen,

These are extracted from exiD lanelet2 hdmap files. I have added a few examples here: [exid_lane_markings.zip](https://github.com/SajjadMzf/TrajPreprocess/blob/main/exid_lane_markings.zip)

**Comment by luwen2024** [comment]
Thx Sajjad!
